spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:mariadb://192.168.100.216:3306/ysu?characterEncoding=UTF-8&ServerTimezone=UTC
    username: root
    password: Laonpp00..L
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

logging:
  level:
    root: info
    org:
      hibernate:
        type: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

app:
  filePath: /Users/stanjoo/Documents/laonstory/ysu/upload