spring:
  security:
    jwt:
      secret: dustpeogkrry
  profiles:
    active: local
  jpa:
    properties:
      hibernate.default_batch_fetch_size: 1000

server:
  port: 6000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true